name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
        
      - name: List files
        run: ls -la 
        
      - name: Run tests
        run: ./tp4_test
